# Site settings
# Enter your own credentials here
title: "Data science solutions to XRD"
email: abhiram.kannan@gatech.edu
description: >
  Tell us about your site
baseurl: "/MIC-XRD-Polymer" # replace ``/research-pages`` with the name of the parents repository
url: "phelpsforpresident.tmp.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
#twitter_username: twitterhandle
disqus: phelpsforpresident

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: phelpsforpresident
  repo: MIC-XRD-Polymer
  # Branch hosting Github pages
  branch: gh-pages
